services:
  auth-postgres:
    image: postgres:16-alpine
    container_name: auth-postgres
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
    ports:
      - "5432:5432"
    volumes:
      - auth-postgres-data:/var/lib/postgresql/data

  account-postgres:
    image: postgres:16-alpine
    container_name: account-postgres
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: account_user
      POSTGRES_PASSWORD: account_pass
    ports:
      - "5433:5432"
    volumes:
      - account-postgres-data:/var/lib/postgresql/data

  payment-postgres:
    image: postgres:16-alpine
    container_name: payment-postgres
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: payment_pass
    ports:
      - "5434:5432"
    volumes:
      - payment-postgres-data:/var/lib/postgresql/data

  ledger-postgres:
    image: postgres:16-alpine
    container_name: ledger-postgres
    environment:
      POSTGRES_DB: ledger_db
      POSTGRES_USER: ledger_user
      POSTGRES_PASSWORD: ledger_pass
    ports:
      - "5435:5432"
    volumes:
      - ledger-postgres-data:/var/lib/postgresql/data

  notification-postgres:
    image: postgres:16-alpine
    container_name: notification-postgres
    environment:
      POSTGRES_DB: notification_db
      POSTGRES_USER: notification_user
      POSTGRES_PASSWORD: notification_pass
    ports:
      - "5436:5432"
    volumes:
      - notification-postgres-data:/var/lib/postgresql/data

  audit-postgres:
    image: postgres:16-alpine
    container_name: audit-postgres
    environment:
      POSTGRES_DB: audit_db
      POSTGRES_USER: audit_user
      POSTGRES_PASSWORD: audit_pass
    ports:
      - "5437:5432"
    volumes:
      - audit-postgres-data:/var/lib/postgresql/data

  kafka:
    image: apache/kafka:3.7.0
    container_name: payment-ledger-kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
    ports:
      - "9092:9092"

  redis:
    image: redis:7-alpine
    container_name: payment-ledger-redis
    ports:
      - "6379:6379"

volumes:
  auth-postgres-data:
  account-postgres-data:
  payment-postgres-data:
  ledger-postgres-data:
  notification-postgres-data:
  audit-postgres-data:
