server:
  port: 8084

spring:
  application:
    name: ledger-service
  datasource:
    url: jdbc:postgresql://localhost:5435/ledger_db
    username: ledger_user
    password: ledger_pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ledger-service
    producer:
      client-id: ledger-service

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
